export const sympthoms = [
    { value: "1", label: "Ból głowy" },
    { value: "2", label: "Bóle mięśni" },
    { value: "3", label: "Ból brzucha" },
    { value: "4", label: "Nudności, wymioty" },
    { value: "5", label: "Gorączka, dreszcze" },
    { value: "6", label: "Powiększone węzły chłonne" },
    { value: "7", label: "Wysypka" },
    { value: "8", label: "Katar, zatkany nos" },
    { value: "9", label: "Kaszel, chrypka" },
    { value: "10", label: "Ból ucha" },
    { value: "11", label: "Ból kręgosłupa/pleców" },
    { value: "12", label: "Zmęczenie, senność" },
    { value: "13", label: "Problemy ze snem" },
    { value: "14", label: "Obrzęk, ból stawów" },
    { value: "15", label: "Bóle zębów" },
    { value: "16", label: "Drętwienie kończyn" },
    { value: "17", label: "Świąd skóry" },
    { value: "18", label: "Skurcze mięśni, szczękościsk" },
    { value: "19", label: "Utrata węchu" },
    { value: "20", label: "Krwotok" },
    { value: "21", label: "Odksztuszanie krwi"},
    { value: "22", label: "Łzawiące oczy"},
    { value: "23", label: "Zmęczenie"},
    { value: "24", label: "Częste oddawanie moczu/wypróżnianie się"},
    { value: "25", label: "Rzadkie oddawanie moczu/wypróżnianie się" },
    { value: "26", label: "Utrata czucia"},
    { value: "27", label: "Utrata węchu"},
    { value: "28", label: "Ból szyi" },
    { value: "29", label: "Duszność" }
];